FROM nginx:alpine

# Copy nginx config
COPY docker/nginx-frontend.conf /etc/nginx/conf.d/default.conf

# Copy frontend files
COPY frontend /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
